import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'scorer_dashboard': 'CRIXORA SCORER',
      'welcome': 'Welcome',
      'tournaments': 'Tournaments',
      'manage_score_tournaments': 'Manage & score tournaments',
      'friendly_matches': 'Friendly Matches',
      'individual_matches': 'Individual non-tournament games',
      'profile': 'Profile',
      'account_settings': 'Account details & settings',
      'start_scoring': 'Start Scoring',
      'quick_session': 'Quick ball-by-ball scoring session',
      'my_tournaments': 'My Tournaments',
      'create_tournament': 'Create Tournament',
      'no_tournaments': 'No tournaments yet',
      'create_first_tournament':
          'Create your first tournament and start scoring.',
      'matches': 'Matches',
      'add_match': 'Add Match',
      'no_matches': 'No matches yet',
      'create_match_squads': 'Create a match and set up the squads.',
      'teams': 'Teams',
      'venue': 'Venue',
      'delete_match': 'Delete match?',
      'delete_confirm': 'This will remove the match from the scorer data.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'live': 'LIVE',
      'upcoming': 'UPCOMING',
      'completed': 'COMPLETED',
      'overs': 'overs',
      'local_match': 'Local Match',
      'search_hint': 'Search matches, teams, venue…',
      'no_matches_found': 'No matches found',
      'start_scoring_title': 'Start Scoring',
      'delete_match_permanently':
          'This permanently removes the match and its score data.',
      'home': 'Home',
      'scoring': 'Scoring',
      'set_squads': 'Set Squads',
      'match_not_found': 'Match not found',
      'back': 'Back',
      'in_squad': 'in squad',
      'tap_checkbox': 'Tap the checkbox to include a player in the playing XI.',
      'no_players_yet': 'No players yet — add the squad members for this team.',
      'add_player': 'Add Player',
      'player_name': 'Player Name',
      'saving': 'Saving…',
      'select_min_player': 'Select at least one player for each team',
      'match_info': 'Match Info',
      'toss': 'Toss',
      'opening_players': 'Opening Players',
      'vs': 'vs',
      'enter_venue': 'Enter venue name',
      'set_match_time': 'Set a date & time (optional)',
      'continue_to_toss': 'Continue to Toss',
      'set_opening_players': 'Set Opening Players',
      'exchange_between_teams': 'Exchange Player between Teams',
      'please_fill_info': 'Please fill all match info fields',
      'select_toss_winner': 'Please select the toss winner',
      'select_openers': 'Please select opening batsmen and bowler',
      'innings_break': 'Innings Break',
      'start_second_innings': 'Start 2nd Innings',
      'match_summary': 'Match Summary',
      'wicket_alert': 'Wicket!',
      'fielder_optional': 'Fielder (optional)',
      'confirm_wicket': 'Confirm Wicket',
      'no_bench_players': 'No bench players available',
      'confirm_substitution': 'Confirm Substitution',
      'select_extra_type': 'Select Extra Type',
      'extra_type_hint': 'Tap an extra type first, then choose runs',
      'scoring_choice': 'What would you like to do?',
      'scoring_choice_hint':
          'Pick a tournament to manage teams & fixtures, or set up an individual match.',
      'tournament_card_subtitle':
          'Manage tournaments, teams, players & fixtures',
      'match_card_subtitle':
          'Set up an individual match — venue, teams & players',
      'schedule_match': 'Schedule Match',
      'select_different_teams': 'Select two different teams',
      'enter_venue_error': 'Enter a venue',
      'no_tournament_selected': 'No tournament selected',
      'match_scheduled': 'Match scheduled',
      'no_tournaments_available': 'No tournaments available',
      'create_tournament_hint': 'Create a tournament first.',
      'scheduling': 'Scheduling…',
      'toss_and_openers': 'Toss & Openers',
      'manage_squads': 'Manage Squads / Add Players',
      'toss_winner_query': 'Who won the toss?',
      'toss_decision_query': 'Elected to:',
      'toss_picker_hint':
          'Pick the toss winner to choose the opening batsmen and bowler.',
      'manage_squad': 'Manage Squad',
      'starting': 'Starting…',
      'create_local_match': 'Create Friendly Match',
      'team_a': 'Team A',
      'team_b': 'Team B',
      'create_match_hint':
          'Enter team names manually, or tap the dropdown to pick an existing team.',
      'match_created_success': 'Match created — set up the squads',
      'enter_team_names_error': 'Please enter both team names',
      'different_teams_error': 'Teams must be different',
      'optional_date_time': 'Set date & time (optional)',
      'creating': 'Creating…',
      'select_existing_team': 'Select from existing teams',

      // Tournament Management
      'edit_tournament': 'Edit Tournament',
      'tournament_name': 'Tournament Name',
      'match_format': 'Match Format',
      'overs_per_innings': 'Overs per Innings',
      'tournament_entry_fee': 'Tournament Entry Fee',
      'winner_prize': 'Winner Prize',
      'runner_up_prize': 'Runner-up Prize',
      'points_rules': 'Points Rules',
      'nrr_tiebreaker': 'NRR Tiebreaker',

      // Team & Player Setup
      'team_name': 'Team Name',
      'short_code': 'Short Code',
      'owner_name': 'Owner Name',
      'whatsapp': 'WhatsApp',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'squad': 'Squad',
      'remove_player': 'Remove Player',
      'edit_player': 'Edit Player',
      'role': 'Role',
      'batsman': 'Batsman',
      'bowler': 'Bowler',
      'all_rounder': 'All Rounder',
      'wicket_keeper': 'Wicket Keeper',
      'batting_style': 'Batting Style',
      'bowling_style': 'Bowling Style',

      // Match Setup Wizard
      'select_teams': 'Select Teams',
      'match_time': 'Match Time',
      'format_and_overs': 'Format & Overs',
      'toss_winner': 'Toss Winner',
      'toss_decision': 'Toss Decision',
      'bat': 'Bat',
      'bowl': 'Bowl',
      'opening_striker': 'Opening Striker',
      'opening_non_striker': 'Opening Non-Striker',
      'opening_bowler': 'Opening Bowler',
      'exchange_player': 'Exchange Player',

      // Live Scoring
      'scoreboard': 'Scoreboard',
      'target': 'Target',
      'runs_needed': 'Runs Needed',
      'legal_balls': 'Legal Balls',
      'extras': 'Extras',
      'striker': 'Striker',
      'non_striker': 'Non-Striker',
      'end_match': 'End Match',
      'undo': 'Undo',
      'swap_strike': 'Swap Strike',
      'replace_player': 'Replace Player',
      'wicket': 'Wicket',
      'dismissal_type': 'Dismissal Type',
      'caught': 'Caught',
      'bowled': 'Bowled',
      'lbw': 'LBW',
      'run_out': 'Run Out',
      'stumped': 'Stumped',
      'hit_wicket': 'Hit Wicket',
      'fielder': 'Fielder',

      // Scheduling
      'manual_schedule': 'Manual Schedule',
      'add_stage': 'Add Stage',
      'rename_stage': 'Rename Stage',
      'remove_stage': 'Remove Stage',
      'add_fixture': 'Add Fixture',
      'edit_fixture': 'Edit Fixture',
      'remove_fixture': 'Remove Fixture',
      'declare_result': 'Declare Result',
      'winner': 'Winner',
      'loser_fate': 'Loser Fate',
      'next_stage': 'Next Stage',
      'next_match': 'Next Match',
      'eliminate': 'Eliminate',

      // Common
      'save': 'Save',
      'update': 'Update',
      'confirm': 'Confirm',
      'required': 'Required',
      'loading': 'Loading',
      'no_data': 'No Data',
    },
    'ur': {
      'scorer_dashboard': 'کرکسورا اسکورر',
      'welcome': 'خوش آمدید',
      'tournaments': 'ٹورنامنٹس',
      'manage_score_tournaments': 'ٹورنامنٹس کا انتظام اور اسکورنگ کریں',
      'friendly_matches': 'فرینڈلی میچز',
      'individual_matches': 'انفرادی میچز',
      'profile': 'پروفائل',
      'account_settings': 'اکاؤنٹ کی تفصیلات اور سیٹنگز',
      'start_scoring': 'اسکورنگ شروع کریں',
      'quick_session': 'تیزی سے اسکورنگ شروع کریں',
      'my_tournaments': 'میرے ٹورنامنٹس',
      'create_tournament': 'ٹورنامنٹ بنائیں',
      'no_tournaments': 'ابھی کوئی ٹورنامنٹ نہیں ہے',
      'create_first_tournament': 'پہلا ٹورنامنٹ بنائیں اور اسکورنگ شروع کریں۔',
      'matches': 'میچز',
      'add_match': 'میچ شامل کریں',
      'no_matches': 'ابھی کوئی میچ نہیں ہے',
      'create_match_squads': 'میچ بنائیں اور ٹیمیں تیار کریں۔',
      'teams': 'ٹیمیں',
      'venue': 'مقام',
      'delete_match': 'میچ ختم کریں؟',
      'delete_confirm': 'یہ اسکورر ڈیٹا سے میچ کو ختم کر دے گا۔',
      'cancel': 'منسوخ کریں',
      'delete': 'ختم کریں',
      'live': 'لائیو',
      'upcoming': 'آنے والا',
      'completed': 'مکمل',
      'overs': 'اوورز',
      'local_match': 'مقامی میچ',
      'search_hint': 'میچ، ٹیم، یا مقام تلاش کریں...',
      'no_matches_found': 'کوئی میچ نہیں ملا',
      'start_scoring_title': 'اسکورنگ شروع کریں',
      'delete_match_permanently':
          'یہ مستقل طور پر میچ اور اس کا اسکور ڈیٹا ختم کر دے گا۔',
      'home': 'ہوم',
      'scoring': 'اسکورنگ',
      'set_squads': 'ٹیمیں ترتیب دیں',
      'match_not_found': 'میچ نہیں ملا',
      'back': 'واپس',
      'in_squad': 'اسکواڈ میں',
      'tap_checkbox': 'پلیئنگ الیون میں شامل کرنے کے لیے چیک باکس پر ٹیپ کریں۔',
      'no_players_yet':
          'ابھی کوئی کھلاڑی نہیں ہے - اس ٹیم کے کھلاڑی شامل کریں۔',
      'add_player': 'کھلاڑی شامل کریں',
      'player_name': 'کھلاڑی کا نام',
      'saving': 'محفوظ ہو رہا ہے...',
      'select_min_player': 'ہر ٹیم کے لیے کم از کم ایک کھلاڑی منتخب کریں',
      'match_info': 'میچ کی معلومات',
      'toss': 'ٹاس',
      'opening_players': 'اوپننگ کھلاڑی',
      'vs': 'بمقابلہ',
      'enter_venue': 'مقام کا نام درج کریں',
      'set_match_time': 'وقت اور تاریخ منتخب کریں',
      'continue_to_toss': 'ٹاس پر جائیں',
      'set_opening_players': 'اوپننگ کھلاڑی منتخب کریں',
      'exchange_between_teams': 'ٹیموں کے درمیان کھلاڑی تبدیل کریں',
      'please_fill_info': 'براہ کرم میچ کی تمام معلومات پر کریں',
      'select_toss_winner': 'براہ کرم ٹاس کا فاتح منتخب کریں',
      'select_openers': 'براہ کرم اوپننگ بیٹسمین اور بولر منتخب کریں',
      'innings_break': 'اننگز کا وقفہ',
      'start_second_innings': 'دوسری اننگز شروع کریں',
      'match_summary': 'میچ کا خلاصہ',
      'wicket_alert': 'وکٹ!',
      'fielder_optional': 'فیلڈر (اختیاری)',
      'confirm_wicket': 'وکٹ کی تصدیق کریں',
      'no_bench_players': 'بینچ پر کوئی کھلاڑی دستیاب نہیں ہے',
      'confirm_substitution': 'تبدیلی کی تصدیق کریں',
      'select_extra_type': 'اضافی رنز کی قسم منتخب کریں',
      'extra_type_hint': 'پہلے قسم منتخب کریں، پھر رنز',
      'scoring_choice': 'آپ کیا کرنا چاہیں گے؟',
      'scoring_choice_hint':
          'ٹورنامنٹ کا انتخاب کریں یا انفرادی میچ ترتیب دیں۔',
      'tournament_card_subtitle': 'ٹورنامنٹس، ٹیموں اور میچوں کا انتظام کریں',
      'match_card_subtitle': 'انفرادی میچ ترتیب دیں - مقام، ٹیمیں اور کھلاڑی',
      'schedule_match': 'میچ شیڈول کریں',
      'select_different_teams': 'دو مختلف ٹیمیں منتخب کریں',
      'enter_venue_error': 'مقام درج کریں',
      'no_tournament_selected': 'کوئی ٹورنامنٹ منتخب نہیں کیا گیا',
      'match_scheduled': 'میچ شیڈول ہو گیا',
      'no_tournaments_available': 'کوئی ٹورنامنٹ دستیاب نہیں ہے',
      'create_tournament_hint': 'پہلے ایک ٹورنامنٹ بنائیں۔',
      'scheduling': 'شیڈول ہو رہا ہے...',
      'toss_and_openers': 'ٹاس اور اوپنرز',
      'manage_squads': 'ٹیمیں ترتیب دیں / کھلاڑی شامل کریں',
      'toss_winner_query': 'ٹاس کس نے جیتا؟',
      'toss_decision_query': 'فیصلہ کیا کیا؟',
      'toss_picker_hint':
          'اوپننگ بیٹسمین اور بولر منتخب کرنے کے لیے ٹاس کا فاتح منتخب کریں۔',
      'manage_squad': 'اسکواڈ ترتیب دیں',
      'starting': 'شروع ہو رہا ہے...',
      'create_local_match': 'فرینڈلی میچ بنائیں',
      'team_a': 'ٹیم اے',
      'team_b': 'ٹیم بی',
      'create_match_hint':
          'ٹیم کے نام دستی طور پر درج کریں، یا فہرست سے منتخب کریں۔',
      'match_created_success': 'میچ بن گیا - اب ٹیمیں ترتیب دیں',
      'enter_team_names_error': 'براہ کرم دونوں ٹیموں کے نام درج کریں',
      'different_teams_error': 'ٹیمیں مختلف ہونی چاہئیں',
      'optional_date_time': 'وقت اور تاریخ منتخب کریں (اختیاری)',
      'creating': 'بن رہا ہے...',

      // Tournament Management
      'edit_tournament': 'ٹورنامنٹ میں ترمیم کریں',
      'tournament_name': 'ٹورنامنٹ کا نام',
      'match_format': 'میچ کا فارمیٹ',
      'overs_per_innings': 'اوورز فی اننگز',
      'entry_fees': 'انٹری فیس',
      'cash_prizes': 'نقد انعامات',
      'points_rules': 'پوائنٹس کے اصول',
      'nrr_tiebreaker': 'این آر آر ٹائی بریکر',

      // Team & Player Setup
      'team_name': 'ٹیم کا نام',
      'short_code': 'مختصر کوڈ',
      'owner_name': 'مالک کا نام',
      'whatsapp': 'واٹس ایپ',
      'paid': 'ادائیگی ہو گئی',
      'unpaid': 'ادائیگی نہیں ہوئی',
      'squad': 'اسکواڈ',
      'remove_player': 'کھلاڑی نکالیں',
      'edit_player': 'کھلاڑی میں ترمیم کریں',
      'role': 'کردار',
      'batsman': 'بیٹسمین',
      'bowler': 'بولر',
      'all_rounder': 'آل راؤنڈر',
      'wicket_keeper': 'وکٹ کیپر',
      'batting_style': 'بیٹنگ کا انداز',
      'bowling_style': 'بولنگ کا انداز',

      // Match Setup Wizard
      'select_teams': 'ٹیمیں منتخب کریں',
      'match_time': 'میچ کا وقت',
      'format_and_overs': 'فارمیٹ اور اوورز',
      'toss_winner': 'ٹاس کا فاتح',
      'toss_decision': 'ٹاس کا فیصلہ',
      'bat': 'بیٹنگ',
      'bowl': 'بولنگ',
      'opening_striker': 'اوپننگ اسٹرائیکر',
      'opening_non_striker': 'اوپننگ نان اسٹرائیکر',
      'opening_bowler': 'اوپننگ بولر',
      'exchange_player': 'کھلاڑی تبدیل کریں',

      // Live Scoring
      'scoreboard': 'اسکور بورڈ',
      'target': 'ٹارگٹ',
      'runs_needed': 'درکار رنز',
      'legal_balls': 'قانونی گیندیں',
      'extras': 'ایکسٹرا',
      'striker': 'اسٹرائیکر',
      'non_striker': 'نان اسٹرائیکر',
      'end_match': 'میچ ختم کریں',
      'undo': 'واپس (Undo)',
      'swap_strike': 'اسٹرائیک بدلیں',
      'replace_player': 'کھلاڑی تبدیل کریں',
      'wicket': 'وکٹ',
      'dismissal_type': 'آؤٹ ہونے کی قسم',
      'caught': 'کیچ آؤٹ',
      'bowled': 'بولڈ',
      'lbw': 'ایل بی ڈبلیو',
      'run_out': 'رن آؤٹ',
      'stumped': 'اسٹمپڈ',
      'hit_wicket': 'ہٹ وکٹ',
      'fielder': 'فیلڈر',

      // Scheduling
      'manual_schedule': 'دستی شیڈول',
      'add_stage': 'مرحلہ شامل کریں',
      'rename_stage': 'مرحلے کا نام بدلیں',
      'remove_stage': 'مرحلہ ختم کریں',
      'add_fixture': 'میچ شامل کریں',
      'edit_fixture': 'میچ میں ترمیم کریں',
      'remove_fixture': 'میچ ختم کریں',
      'declare_result': 'نتیجہ کا اعلان کریں',
      'winner': 'فاتح',
      'loser_fate': 'ہارنے والے کا انجام',
      'next_stage': 'اگلا مرحلہ',
      'next_match': 'اگلا میچ',
      'eliminate': 'باہر (Eliminate)',

      // Common
      'save': 'محفوظ کریں',
      'update': 'اپ ڈیٹ کریں',
      'confirm': 'تصدیق کریں',
      'required': 'ضروری',
      'loading': 'لوڈنگ ہو رہی ہے...',
      'no_data': 'کوئی ڈیٹا نہیں ہے',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ur'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
