import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'scorer_dashboard': 'WICKZYSCORER SCORER',
      'welcome': 'Welcome',
      'tournaments': 'Tournaments',
      'manage_score_tournaments': 'Manage & score tournaments',
      'friendly_matches': 'Friendly Matches',
      'individual_matches': 'Individual non-tournament games',
      'profile': 'Profile',
      'account_settings': 'Account details & settings',
      'start_scoring': 'Start Scoring',
      'quick_session': 'Quick ball-by-ball scoring session',
      'my_tournaments': 'My Tournaments',
      'create_tournament': 'Create Tournament',
      'no_tournaments': 'No tournaments yet',
      'create_first_tournament':
          'Create your first tournament and start scoring.',
      'matches': 'Matches',
      'add_match': 'Add Match',
      'no_matches': 'No matches yet',
      'create_match_squads': 'Create a match and set up the squads.',
      'teams': 'Teams',
      'venue': 'Venue',
      'organizer': 'Organizer',
      'delete_match': 'Delete match?',
      'delete_confirm': 'This will remove the match from the scorer data.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'live': 'LIVE',
      'upcoming': 'UPCOMING',
      'completed': 'COMPLETED',
      'overs': 'overs',
      'note_optional': 'Note (optional)',
      'this_over': 'This Over',
      'balls_left': 'Balls Left',
      'adjust_overs': 'Adjust Overs',
      'player_of_match': 'Player of the Match',
      'best_batsman': 'Best Batsman',
      'best_bowler': 'Best Bowler',
      'finish_match': 'Finish Match',
      'close': 'Close',
      'select_award_player': 'Select player to give award',
      'innings1': '1st Innings',
      'innings2': '2nd Innings',
      'won_by': 'won by',
      'lost_by': 'lost by',
      'match_no_result': 'No Result',
      'wickets': 'wickets',
      'runs': 'runs',
      'no_players': 'No players available',
      'local_match': 'Local Match',
      'search_hint': 'Search matches, teams, venue…',
      'no_matches_found': 'No matches found',
      'tournament_matches': 'Tournament Matches',
      'no_friendly_matches': 'No friendly matches yet',
      'no_tournament_matches': 'No tournament matches yet',
      'start_scoring_title': 'Start Scoring',
      'delete_match_permanently':
          'This permanently removes the match and its score data.',
      'home': 'Home',
      'scoring': 'Scoring',
      'set_squads': 'Set Squads',
      'match_not_found': 'Match not found',
      'back': 'Back',
      'in_squad': 'in squad',
      'tap_checkbox': 'Tap the checkbox to include a player in the playing XI.',
      'no_players_yet': 'No players yet — add the squad members for this team.',
      'add_player': 'Add Player',
      'player_name': 'Player Name',
      'saving': 'Saving…',
      'select_min_player': 'Select at least one player for each team',
      'match_info': 'Match Info',
      'toss': 'Toss',
      'opening_players': 'Opening Players',
      'vs': 'vs',
      'enter_venue': 'Enter venue name',
      'set_match_time': 'Set a date & time (optional)',
      'continue_to_toss': 'Continue to Toss',
      'set_opening_players': 'Set Opening Players',
      'exchange_between_teams': 'Exchange Player between Teams',
      'please_fill_info': 'Please fill all match info fields',
      'select_toss_winner': 'Please select the toss winner',
      'select_openers': 'Please select opening batsmen and bowler',
      'innings_break': 'Innings Break',
      'start_second_innings': 'Start 2nd Innings',
      'innings_complete': 'Innings is complete. Start the next innings.',
      'match_tied': 'Match Tied!',
      'super_over_question':
          'The match is tied. Do you want to start the Super Over?',
      'start_super_over': 'Start Super Over',
      'no': 'No',
      'yes': 'Yes',
      'super_over_setup': 'Super Over Setup',
      'who_bats_first': 'Who bats first in the Super Over?',
      'super_over_description':
          'Each team bats one over of 6 balls. The team with the higher score '
              'after both overs wins the match. Choose the batting team, then tap '
              'Strike / Non-S for the two batters and pick a bowler.',
      'start_match': 'Start Match',
      'super_over_banner': 'Super Over',
      'complete_match': 'Complete Match',
      'award': 'Award',
      'award_prizes': 'Award Prizes',
      'player_of_match_prize': 'Player of the Match prize',
      'best_batsman_prize': 'Best Batsman prize',
      'best_bowler_prize': 'Best Bowler prize',
      'prize_optional': 'Prize (optional)',
      'award_winner': 'Award Winner',
      'save_awards': 'Save Awards',
      'show_all_players': 'Show all players',
      'show_less': 'Show less',
      'custom_awards': 'Custom Awards',
      'add_custom_award': 'Add Custom Category',
      'category_name': 'Category name',
      'add': 'Add',
      'choose_winner': 'Choose Winner',
      'tap_to_choose_winner': 'Tap to choose winner',
      'best_fielder': 'Best Fielder',
      'best_wicket_keeper': 'Best Wicket Keeper',
      'most_sixes': 'Most Sixes',
      'most_fours': 'Most Fours',
      'best_strike_rate': 'Best Strike Rate',
      'best_economy': 'Best Economy',
      'match_summary': 'Match Summary',
      'wicket_alert': 'Wicket!',
      'fielder_optional': 'Fielder (optional)',
      'confirm_wicket': 'Confirm Wicket',
      'no_bench_players': 'No bench players available',
      'confirm_substitution': 'Confirm Substitution',
      'select_extra_type': 'Select Extra Type',
      'extra_type_hint': 'Tap an extra type first, then choose runs',
      'scoring_choice': 'What would you like to do?',
      'scoring_choice_hint':
          'Pick a tournament to manage teams & fixtures, or set up an individual match.',
      'tournament_card_subtitle':
          'Tap a tournament to jump straight into its upcoming matches',
      'match_card_subtitle':
          'Set up an individual match — venue, teams & players',
      'schedule_match': 'Schedule Match',
      'select_different_teams': 'Select two different teams',
      'enter_venue_error': 'Enter a venue',
      'no_tournament_selected': 'No tournament selected',
      'match_scheduled': 'Match scheduled',
      'no_tournaments_available': 'No tournaments available',
      'create_tournament_hint': 'Create a tournament first.',
      'scheduling': 'Scheduling…',
      'toss_and_openers': 'Toss & Openers',
      'manage_squads': 'Manage Squads / Add Players',
      'toss_winner_query': 'Who won the toss?',
      'toss_decision_query': 'Elected to:',
      'toss_picker_hint':
          'Pick the toss winner to choose the opening batsmen and bowler.',
      'manage_squad': 'Manage Squad',
      'starting': 'Starting…',
      'create_local_match': 'Create Friendly Match',
      'team_a': 'Team A',
      'team_b': 'Team B',
      'create_match_hint':
          'Enter team names manually, or tap the dropdown to pick an existing team.',
      'match_created_success': 'Match created — set up the squads',
      'enter_team_names_error': 'Please enter both team names',
      'different_teams_error': 'Teams must be different',
      'optional_date_time': 'Set date & time (optional)',
      'creating': 'Creating…',
      'select_existing_team': 'Select from existing teams',

      // Tournament Management
      'edit_tournament': 'Edit Tournament',
      'tournament_name': 'Tournament Name',
      'match_format': 'Match Format',
      'overs_per_innings': 'Overs per Innings',
      'tournament_entry_fee': 'Tournament Entry Fee',
      'winner_prize': 'Winner Prize',
      'runner_up_prize': 'Runner-up Prize',
      'points_rules': 'Points Rules',
      'nrr_tiebreaker': 'NRR Tiebreaker',

      // Team & Player Setup
      'team_name': 'Team Name',
      'short_code': 'Short Code',
      'owner_name': 'Owner Name',
      'whatsapp': 'WhatsApp',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'squad': 'Squad',
      'remove_player': 'Remove Player',
      'edit_player': 'Edit Player',
      'role': 'Role',
      'batsman': 'Batsman',
      'bowler': 'Bowler',
      'all_rounder': 'All Rounder',
      'wicket_keeper': 'Wicket Keeper',
      'batting_style': 'Batting Style',
      'bowling_style': 'Bowling Style',

      // Match Setup Wizard
      'select_teams': 'Select Teams',
      'match_time': 'Match Time',
      'format_and_overs': 'Format & Overs',
      'toss_winner': 'Toss Winner',
      'toss_decision': 'Toss Decision',
      'bat': 'Bat',
      'bowl': 'Bowl',
      'opening_striker': 'Opening Striker',
      'opening_non_striker': 'Opening Non-Striker',
      'opening_bowler': 'Opening Bowler',
      'exchange_player': 'Exchange Player',

      // Live Scoring
      'scoreboard': 'Scoreboard',
      'target': 'Target',
      'runs_needed': 'Runs Needed',
      'legal_balls': 'Legal Balls',
      'extras': 'Extras',
      'striker': 'Striker',
      'non_striker': 'Non-Striker',
      'end_match': 'End Match',
      'pause_match': 'Pause',
      'pause_match_confirm':
          'Pause this match? You can resume it later from the Matches tab.',
      'undo': 'Undo',
      'swap_strike': 'Swap Strike',
      'replace_player': 'Replace Player',
      'wicket': 'Wicket',
      'dismissal_type': 'Dismissal Type',
      'caught': 'Caught',
      'bowled': 'Bowled',
      'lbw': 'LBW',
      'run_out': 'Run Out',
      'stumped': 'Stumped',
      'hit_wicket': 'Hit Wicket',
      'fielder': 'Fielder',
      'next_over': 'Next Over',
      'who_will_bowl_next': 'Who will bowl the next over?',
      'retired_hurt': 'Retired Hurt',
      'retired_hurt_confirm':
          'This bowler can no longer bowl in this innings. Select a replacement to continue scoring.',
      'select_bowler_to_continue': 'Select a bowler to continue scoring.',
      'select_bowler_first': 'Select a bowler first',
      'change_bowler_hint':
          'Change the current bowler or mark them retired hurt.',
      'available_bowlers': 'Available Bowlers',
      'next_batsman': 'Next Batsman',
      'who_comes_to_bat': 'Who comes in to bat?',
      'no_batsmen_available':
          'No players available to bat. Add players to the batting team first.',

      // Scheduling
      'manual_schedule': 'Manual Schedule',
      'add_stage': 'Add Stage',
      'rename_stage': 'Rename Stage',
      'remove_stage': 'Remove Stage',
      'add_fixture': 'Add Fixture',
      'edit_fixture': 'Edit Fixture',
      'remove_fixture': 'Remove Fixture',
      'declare_result': 'Declare Result',
      'winner': 'Winner',
      'loser_fate': 'Loser Fate',
      'next_stage': 'Next Stage',
      'next_match': 'Next Match',
      'eliminate': 'Eliminate',
      'eliminated': 'Eliminated',
      'waiting_for_opponent': 'Waiting for opponent',
      'next_match_ready': 'Next match ready',
      'advances_to': 'Advances to',
      'qualified': 'Qualified',
      'champion': 'Champion',
      'tournament_progress': 'Tournament Progress',
      'progression_hint': 'See how both teams continue in this tournament.',
      'continue': 'Continue',
      'progression': 'Progression',
      'winner_destination': 'Winner goes to',
      'loser_destination': 'Loser goes to',
      'target_fixture': 'Destination match',
      'target_stage': 'Destination stage',

      // Direct Tournament Schedule Flow
      'select_tournament': 'Select Tournament',
      'upcoming_matches': 'Upcoming Matches',
      'no_schedule': 'No Schedule',
      'schedule': 'Schedule',
      'match_number': 'Match',
      'no_upcoming_matches': 'No upcoming matches',
      'scheduled': 'Scheduled',
      'match_schedule': 'Match Schedule',
      'build_schedule': 'Build Schedule',
      'build_schedule_hint':
          'No matches scheduled yet. Build a stage-wise schedule to set up fixtures.',
      'awaiting_result': 'Awaiting Result',

      // Common
      'save': 'Save',
      'update': 'Update',
      'confirm': 'Confirm',
      'required': 'Required',
      'loading': 'Loading',
      'no_data': 'No Data',
    },
    'ur': {
      'scorer_dashboard': 'وکسزی اسکورر',
      'welcome': 'خوش آمدید',
      'tournaments': 'ٹورنامنٹس',
      'manage_score_tournaments': 'ٹورنامنٹس کا انتظام اور اسکورنگ کریں',
      'friendly_matches': 'فرینڈلی میچز',
      'individual_matches': 'انفرادی میچز',
      'profile': 'پروفائل',
      'account_settings': 'اکاؤنٹ کی تفصیلات اور سیٹنگز',
      'start_scoring': 'اسکورنگ شروع کریں',
      'quick_session': 'تیزی سے اسکورنگ شروع کریں',
      'my_tournaments': 'میرے ٹورنامنٹس',
      'create_tournament': 'ٹورنامنٹ بنائیں',
      'no_tournaments': 'ابھی کوئی ٹورنامنٹ نہیں ہے',
      'create_first_tournament': 'پہلا ٹورنامنٹ بنائیں اور اسکورنگ شروع کریں۔',
      'matches': 'میچز',
      'add_match': 'میچ شامل کریں',
      'no_matches': 'ابھی کوئی میچ نہیں ہے',
      'create_match_squads': 'میچ بنائیں اور ٹیمیں تیار کریں۔',
      'teams': 'ٹیمیں',
      'venue': 'مقام',
      'organizer': 'آرگنائزر',
      'delete_match': 'میچ ختم کریں؟',
      'delete_confirm': 'یہ اسکورر ڈیٹا سے میچ کو ختم کر دے گا۔',
      'cancel': 'منسوخ کریں',
      'delete': 'ختم کریں',
      'live': 'لائیو',
      'upcoming': 'آنے والا',
      'completed': 'مکمل',
      'overs': 'اوورز',
      'note_optional': 'نوٹ (اختیاری)',
      'this_over': 'یہ اوور',
      'balls_left': 'بقیہ گیندیں',
      'adjust_overs': 'اوورز ایڈجسٹ کریں',
      'player_of_match': 'مین آف دی میچ',
      'best_batsman': 'بہترین بلے باز',
      'best_bowler': 'بہترین گیند باز',
      'finish_match': 'میچ ختم کریں',
      'close': 'بند کریں',
      'select_award_player': 'کھلاڑی کا انتخاب کریں',
      'innings1': 'پہلی اننگز',
      'innings2': 'دوسری اننگز',
      'won_by': 'سے جیت گیا',
      'lost_by': 'سے ہار گیا',
      'match_no_result': 'کوئی نتیجہ نہیں',
      'wickets': 'وکٹیں',
      'runs': 'رنز',
      'no_players': 'کوئی کھلاڑی دستیاب نہیں',
      'local_match': 'مقامی میچ',
      'search_hint': 'میچ، ٹیم، یا مقام تلاش کریں...',
      'no_matches_found': 'کوئی میچ نہیں ملا',
      'tournament_matches': 'ٹورنامنٹ میچز',
      'no_friendly_matches': 'ابھی کوئی فرینڈلی میچ نہیں',
      'no_tournament_matches': 'ابھی کوئی ٹورنامنٹ میچ نہیں',
      'start_scoring_title': 'اسکورنگ شروع کریں',
      'delete_match_permanently':
          'یہ مستقل طور پر میچ اور اس کا اسکور ڈیٹا ختم کر دے گا۔',
      'home': 'ہوم',
      'scoring': 'اسکورنگ',
      'set_squads': 'ٹیمیں ترتیب دیں',
      'match_not_found': 'میچ نہیں ملا',
      'back': 'واپس',
      'in_squad': 'اسکواڈ میں',
      'tap_checkbox': 'پلیئنگ الیون میں شامل کرنے کے لیے چیک باکس پر ٹیپ کریں۔',
      'no_players_yet':
          'ابھی کوئی کھلاڑی نہیں ہے - اس ٹیم کے کھلاڑی شامل کریں۔',
      'add_player': 'کھلاڑی شامل کریں',
      'player_name': 'کھلاڑی کا نام',
      'saving': 'محفوظ ہو رہا ہے...',
      'select_min_player': 'ہر ٹیم کے لیے کم از کم ایک کھلاڑی منتخب کریں',
      'match_info': 'میچ کی معلومات',
      'toss': 'ٹاس',
      'opening_players': 'اوپننگ کھلاڑی',
      'vs': 'بمقابلہ',
      'enter_venue': 'مقام کا نام درج کریں',
      'set_match_time': 'وقت اور تاریخ منتخب کریں',
      'continue_to_toss': 'ٹاس پر جائیں',
      'set_opening_players': 'اوپننگ کھلاڑی منتخب کریں',
      'exchange_between_teams': 'ٹیموں کے درمیان کھلاڑی تبدیل کریں',
      'please_fill_info': 'براہ کرم میچ کی تمام معلومات پر کریں',
      'select_toss_winner': 'براہ کرم ٹاس کا فاتح منتخب کریں',
      'select_openers': 'براہ کرم اوپننگ بیٹسمین اور بولر منتخب کریں',
      'innings_break': 'اننگز کا وقفہ',
      'start_second_innings': 'دوسری اننگز شروع کریں',
      'innings_complete': 'اننگز مکمل ہے۔ اگلی اننگز شروع کریں۔',
      'match_tied': 'میچ برابر ہو گیا!',
      'super_over_question':
          'میچ برابر ہے۔ کیا آپ سپر اوور شروع کرنا چاہیں گے؟',
      'start_super_over': 'سپر اوور شروع کریں',
      'no': 'نہیں',
      'yes': 'ہاں',
      'super_over_setup': 'سپر اوور سیٹ اپ',
      'who_bats_first': 'سپر اوور میں پہلے کون بیٹنگ کرے گا؟',
      'super_over_description':
          'ہر ٹیم 6 گیندوں کا ایک اوور کھیلتی ہے۔ دونوں اوور کے بعد جس ٹیم کے '
              'زیادہ رنز ہوں گے وہ میچ جیت جائے گی۔ بیٹنگ ٹیم منتخب کریں، پھر دو '
              'کھلاڑیوں کو سٹرائیک/نان سٹرائیک کے طور پر منتخب کریں اور ایک بولر چنیں۔',
      'start_match': 'میچ شروع کریں',
      'super_over_banner': 'سپر اوور',
      'complete_match': 'میچ مکمل کریں',
      'award': 'اعزاز',
      'award_prizes': 'اعزازات دیں',
      'player_of_match_prize': 'بہترین کھلاڑی کا انعام',
      'best_batsman_prize': 'بہترین بیٹسمین کا انعام',
      'best_bowler_prize': 'بہترین بولر کا انعام',
      'prize_optional': 'انعام (اختیاری)',
      'award_winner': 'فاتح کو اعزاز دیں',
      'save_awards': 'اعزازات محفوظ کریں',
      'show_all_players': 'تمام کھلاڑی دکھائیں',
      'show_less': 'کم دکھائیں',
      'custom_awards': 'اپنی مرضی کے اعزازات',
      'add_custom_award': 'اپنی مرضی کا زمرہ شامل کریں',
      'category_name': 'زمرہ کا نام',
      'add': 'شامل کریں',
      'choose_winner': 'فاتح منتخب کریں',
      'tap_to_choose_winner': 'فاتح منتخب کرنے کے لیے ٹیپ کریں',
      'best_fielder': 'بہترین فیلڈر',
      'best_wicket_keeper': 'بہترین وکٹ کیپر',
      'most_sixes': 'سب سے زیادہ چھکے',
      'most_fours': 'سب سے زیادہ چوکے',
      'best_strike_rate': 'بہترین سٹرائیک ریٹ',
      'best_economy': 'بہترین اکانومی',
      'match_summary': 'میچ کا خلاصہ',
      'wicket_alert': 'وکٹ!',
      'fielder_optional': 'فیلڈر (اختیاری)',
      'confirm_wicket': 'وکٹ کی تصدیق کریں',
      'no_bench_players': 'بینچ پر کوئی کھلاڑی دستیاب نہیں ہے',
      'confirm_substitution': 'تبدیلی کی تصدیق کریں',
      'select_extra_type': 'اضافی رنز کی قسم منتخب کریں',
      'extra_type_hint': 'پہلے قسم منتخب کریں، پھر رنز',
      'scoring_choice': 'آپ کیا کرنا چاہیں گے؟',
      'scoring_choice_hint':
          'ٹورنامنٹ کا انتخاب کریں یا انفرادی میچ ترتیب دیں۔',
      'tournament_card_subtitle':
          'ٹورنامنٹ منتخب کریں اور اس کے آنے والے میچ دیکھیں',
      'match_card_subtitle': 'انفرادی میچ ترتیب دیں - مقام، ٹیمیں اور کھلاڑی',
      'schedule_match': 'میچ شیڈول کریں',
      'select_different_teams': 'دو مختلف ٹیمیں منتخب کریں',
      'enter_venue_error': 'مقام درج کریں',
      'no_tournament_selected': 'کوئی ٹورنامنٹ منتخب نہیں کیا گیا',
      'match_scheduled': 'میچ شیڈول ہو گیا',
      'no_tournaments_available': 'کوئی ٹورنامنٹ دستیاب نہیں ہے',
      'create_tournament_hint': 'پہلے ایک ٹورنامنٹ بنائیں۔',
      'scheduling': 'شیڈول ہو رہا ہے...',
      'toss_and_openers': 'ٹاس اور اوپنرز',
      'manage_squads': 'ٹیمیں ترتیب دیں / کھلاڑی شامل کریں',
      'toss_winner_query': 'ٹاس کس نے جیتا؟',
      'toss_decision_query': 'فیصلہ کیا کیا؟',
      'toss_picker_hint':
          'اوپننگ بیٹسمین اور بولر منتخب کرنے کے لیے ٹاس کا فاتح منتخب کریں۔',
      'manage_squad': 'اسکواڈ ترتیب دیں',
      'starting': 'شروع ہو رہا ہے...',
      'create_local_match': 'فرینڈلی میچ بنائیں',
      'team_a': 'ٹیم اے',
      'team_b': 'ٹیم بی',
      'create_match_hint':
          'ٹیم کے نام دستی طور پر درج کریں، یا فہرست سے منتخب کریں۔',
      'match_created_success': 'میچ بن گیا - اب ٹیمیں ترتیب دیں',
      'enter_team_names_error': 'براہ کرم دونوں ٹیموں کے نام درج کریں',
      'different_teams_error': 'ٹیمیں مختلف ہونی چاہئیں',
      'optional_date_time': 'وقت اور تاریخ منتخب کریں (اختیاری)',
      'creating': 'بن رہا ہے...',

      // Tournament Management
      'edit_tournament': 'ٹورنامنٹ میں ترمیم کریں',
      'tournament_name': 'ٹورنامنٹ کا نام',
      'match_format': 'میچ کا فارمیٹ',
      'overs_per_innings': 'اوورز فی اننگز',
      'entry_fees': 'انٹری فیس',
      'cash_prizes': 'نقد انعامات',
      'points_rules': 'پوائنٹس کے اصول',
      'nrr_tiebreaker': 'این آر آر ٹائی بریکر',

      // Team & Player Setup
      'team_name': 'ٹیم کا نام',
      'short_code': 'مختصر کوڈ',
      'owner_name': 'مالک کا نام',
      'whatsapp': 'واٹس ایپ',
      'paid': 'ادائیگی ہو گئی',
      'unpaid': 'ادائیگی نہیں ہوئی',
      'squad': 'اسکواڈ',
      'remove_player': 'کھلاڑی نکالیں',
      'edit_player': 'کھلاڑی میں ترمیم کریں',
      'role': 'کردار',
      'batsman': 'بیٹسمین',
      'bowler': 'بولر',
      'all_rounder': 'آل راؤنڈر',
      'wicket_keeper': 'وکٹ کیپر',
      'batting_style': 'بیٹنگ کا انداز',
      'bowling_style': 'بولنگ کا انداز',

      // Match Setup Wizard
      'select_teams': 'ٹیمیں منتخب کریں',
      'match_time': 'میچ کا وقت',
      'format_and_overs': 'فارمیٹ اور اوورز',
      'toss_winner': 'ٹاس کا فاتح',
      'toss_decision': 'ٹاس کا فیصلہ',
      'bat': 'بیٹنگ',
      'bowl': 'بولنگ',
      'opening_striker': 'اوپننگ اسٹرائیکر',
      'opening_non_striker': 'اوپننگ نان اسٹرائیکر',
      'opening_bowler': 'اوپننگ بولر',
      'exchange_player': 'کھلاڑی تبدیل کریں',

      // Live Scoring
      'scoreboard': 'اسکور بورڈ',
      'target': 'ٹارگٹ',
      'runs_needed': 'درکار رنز',
      'legal_balls': 'قانونی گیندیں',
      'extras': 'ایکسٹرا',
      'striker': 'اسٹرائیکر',
      'non_striker': 'نان اسٹرائیکر',
      'end_match': 'میچ ختم کریں',
      'pause_match': 'روکیں',
      'pause_match_confirm':
          'کیا یہ میچ روک دیا جائے؟ آپ اسے بعد میں میچز ٹیب سے جاری رکھ سکتے ہیں۔',
      'undo': 'واپس (Undo)',
      'swap_strike': 'اسٹرائیک بدلیں',
      'replace_player': 'کھلاڑی تبدیل کریں',
      'wicket': 'وکٹ',
      'dismissal_type': 'آؤٹ ہونے کی قسم',
      'caught': 'کیچ آؤٹ',
      'bowled': 'بولڈ',
      'lbw': 'ایل بی ڈبلیو',
      'run_out': 'رن آؤٹ',
      'stumped': 'اسٹمپڈ',
      'hit_wicket': 'ہٹ وکٹ',
      'fielder': 'فیلڈر',
      'next_over': 'اگلا اوور',
      'who_will_bowl_next': 'اگلا اوور کون بولے گا؟',
      'retired_hurt': 'ریٹائرڈ ہرٹ',
      'retired_hurt_confirm':
          'یہ بولر اس اننگز میں مزید بولنگ نہیں کر سکے گا۔ اسکورنگ جاری رکھنے کے لیے نیا بولر منتخب کریں۔',
      'select_bowler_to_continue': 'اسکورنگ جاری رکھنے کے لیے بولر منتخب کریں۔',
      'select_bowler_first': 'پہلے بولر منتخب کریں',
      'change_bowler_hint':
          'موجودہ بولر کو تبدیل کریں یا انہیں ریٹائرڈ ہرٹ کریں۔',
      'available_bowlers': 'دستیاب بولرز',
      'next_batsman': 'اگلا بیٹسمین',
      'who_comes_to_bat': 'کون بیٹنگ کرنے آئے گا؟',
      'no_batsmen_available':
          'بیٹنگ کے لیے کوئی کھلاڑی دستیاب نہیں۔ پہلے بیٹنگ ٹیم میں کھلاڑی شامل کریں۔',

      // Scheduling
      'manual_schedule': 'دستی شیڈول',
      'add_stage': 'مرحلہ شامل کریں',
      'rename_stage': 'مرحلے کا نام بدلیں',
      'remove_stage': 'مرحلہ ختم کریں',
      'add_fixture': 'میچ شامل کریں',
      'edit_fixture': 'میچ میں ترمیم کریں',
      'remove_fixture': 'میچ ختم کریں',
      'declare_result': 'نتیجہ کا اعلان کریں',
      'winner': 'فاتح',
      'loser_fate': 'ہارنے والے کا انجام',
      'next_stage': 'اگلا مرحلہ',
      'next_match': 'اگلا میچ',
      'eliminate': 'باہر (Eliminate)',
      'eliminated': 'باہر ہو گئی',
      'waiting_for_opponent': 'مخالف کا انتظار',
      'next_match_ready': 'اگلا میچ تیار',
      'advances_to': 'آگے بڑھتی ہے',
      'qualified': 'کوالیفائی',
      'champion': 'چیمپئن',
      'tournament_progress': 'ٹورنامنٹ پیش رفت',
      'progression_hint':
          'دیکھیں کہ دونوں ٹیمیں اس ٹورنامنٹ میں کیسے آگے بڑھتی ہیں۔',
      'continue': 'جاری رکھیں',
      'progression': 'اگلا مرحلہ',
      'winner_destination': 'فاتح جائے گا',
      'loser_destination': 'ہارنے والا جائے گا',
      'target_fixture': 'منزل میچ',
      'target_stage': 'منزل مرحلہ',

      // Direct Tournament Schedule Flow
      'select_tournament': 'ٹورنامنٹ منتخب کریں',
      'upcoming_matches': 'آنے والے میچز',
      'no_schedule': 'شیڈول نہیں',
      'schedule': 'شیڈول',
      'match_number': 'میچ',
      'no_upcoming_matches': 'کوئی آنے والا میچ نہیں',
      'scheduled': 'شیڈول شدہ',
      'match_schedule': 'میچ شیڈول',
      'build_schedule': 'شیڈول بنائیں',
      'build_schedule_hint':
          'ابھی کوئی میچ شیڈول نہیں۔ مرحلہ وار شیڈول بنا کر فکسچر ترتیب دیں۔',
      'awaiting_result': 'نتیجہ زیر التوا',

      // Common
      'save': 'محفوظ کریں',
      'update': 'اپ ڈیٹ کریں',
      'confirm': 'تصدیق کریں',
      'required': 'ضروری',
      'loading': 'لوڈنگ ہو رہی ہے...',
      'no_data': 'کوئی ڈیٹا نہیں ہے',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ur'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
